export const PROTOCOL_VERSION = 1 as const;
export const ROOM_CAPACITY = 30;
export const ROOM_CODE_MIN = 100;
export const ROOM_CODE_MAX = 999;
export const DEFAULT_DURATION_SECONDS = 60;
export const MIN_DURATION_SECONDS = 20;
export const MAX_DURATION_SECONDS = 180;
export const DURATION_STEP_SECONDS = 5;
export const HOST_ABSENCE_TTL_MS = 30 * 60 * 1000;
export const MAX_CLIENT_MESSAGE_BYTES = 16 * 1024;
export const MAX_STROKE_BATCH_BYTES = 8 * 1024;
export const MAX_SNAPSHOT_CHUNK_BYTES = 64 * 1024;
export const MAX_POINTS_PER_BATCH = 64;
export const MAX_POINTS_PER_STROKE = 2048;
export const MAX_STROKES_PER_DRAWING = 1000;
export const MAX_POINTS_PER_DRAWING = 50_000;
export const MAX_DRAWING_BYTES = 4 * 1024 * 1024;
export const MAX_GUESS_FEED = 100;
export const QUEUE_CAPACITY = 200;
export const SLOW_CONNECTION_BYTES = 256 * 1024;
export const RECOVERED_CONNECTION_BYTES = 128 * 1024;
export const FAILED_CONNECTION_BYTES = 1024 * 1024;
export const HEARTBEAT_INTERVAL_MS = 45_000;
export const HEARTBEAT_TIMEOUT_MS = 90_000;

export const PALETTE = {
  BLACK: { hex: '#111827', label: '검정' },
  BLUE: { hex: '#0072B2', label: '파랑' },
  ORANGE: { hex: '#E69F00', label: '주황' },
  GREEN: { hex: '#009E73', label: '초록' },
  VERMILION: { hex: '#D55E00', label: '다홍' },
  PURPLE: { hex: '#7B2CBF', label: '보라' }
} as const;

export const STROKE_WIDTHS = {
  THIN: 0.003,
  MEDIUM: 0.007,
  THICK: 0.014
} as const;

export const CLIENT_EVENT_TYPES = [
  'CREATE_ROOM',
  'JOIN_ROOM',
  'LEAVE_ROOM',
  'SET_ROUND_DURATION',
  'SET_ANSWER_MODE',
  'SET_KEYWORD_AND_START',
  'SUBMIT_GUESS',
  'DRAW_STROKE_BATCH',
  'UNDO_LAST_STROKE',
  'CLEAR_DRAWING',
  'ASSIGN_DRAWER',
  'RECLAIM_DRAWER',
  'KICK_PLAYER',
  'START_NEXT_ROUND',
  'RETURN_TO_WAITING'
] as const;

export const SERVER_EVENT_TYPES = [
  'ROOM_SESSION',
  'PUBLIC_STATE',
  'PRIVATE_STATE',
  'GUESS_SHARED',
  'ROUND_SOLVED',
  'ROUND_EXPIRED',
  'STROKE_BATCH',
  'STROKE_UNDONE',
  'DRAWING_CLEARED',
  'DRAWING_SNAPSHOT',
  'KICKED',
  'PLAYER_KICKED',
  'ROOM_CLOSED',
  'ERROR'
] as const;

export const ALLOWED_ACTIONS = [
  'LEAVE_ROOM',
  'SET_ROUND_DURATION',
  'SET_ANSWER_MODE',
  'SET_KEYWORD_AND_START',
  'SUBMIT_GUESS',
  'DRAW_STROKE_BATCH',
  'UNDO_LAST_STROKE',
  'CLEAR_DRAWING',
  'ASSIGN_DRAWER',
  'RECLAIM_DRAWER',
  'KICK_PLAYER',
  'START_NEXT_ROUND',
  'RETURN_TO_WAITING'
] as const;

export const ERROR_CODES = [
  'INVALID_JSON', 'INVALID_ENVELOPE', 'INVALID_PAYLOAD', 'PAYLOAD_TOO_LARGE',
  'RATE_LIMITED', 'SERVER_BUSY', 'INTERNAL_ERROR', 'ALREADY_IN_ROOM',
  'NOT_IN_ROOM', 'ROOM_NOT_FOUND', 'ROOM_FULL', 'ROOM_CODE_EXHAUSTED',
  'INVALID_ROOM_CODE', 'INVALID_NICKNAME', 'NICKNAME_IN_USE',
  'REENTRY_BLOCKED', 'SESSION_IN_USE', 'INVALID_SESSION', 'FORBIDDEN',
  'NOT_DRAWER', 'INVALID_MODE', 'INVALID_PHASE', 'MIN_PLAYERS',
  'INVALID_DURATION', 'INVALID_KEYWORD', 'INVALID_GUESS', 'GUESS_FORBIDDEN',
  'ROUND_LOCKED', 'ROUND_EXPIRED', 'STALE_ROUND', 'STALE_DRAWING_REVISION',
  'STALE_DRAWER_EPOCH', 'INVALID_STROKE', 'STROKE_STYLE_MISMATCH',
  'STROKE_SEQUENCE_GAP', 'STROKE_LIMIT', 'DRAWING_LIMIT',
  'NO_STROKE_TO_UNDO', 'TARGET_NOT_FOUND', 'TARGET_DISCONNECTED',
  'CANNOT_KICK_PRIVILEGED'
] as const;
